// AUTO-GENERATED by scripts/build-index.mjs. Do not edit by hand.

export type Kind = "usdc" | "eurc";
export type Format = "grant-thornton" | "deloitte";

export type Composition = {
  treasuries: number;
  repos: number;
  cashInFund: number;
  cashAtBanks: number;
  totalReserveFund: number | null;
  totalOther: number | null;
  totalReserveAssets: number | null;
};

export type Series = {
  date: string;
  circulation: number;
  reserveTotal: number;
  composition: Composition | null;
};

export type Report = {
  kind: Kind;
  year: number;
  month: number;
  format: Format;
  reportDates: string[];
  series: Series[];
  warnings: string[];
  sourcePdf: string;
  localPdf: string;
  sourceUrl: string;
  overrideNote?: string;
};

import r0 from "../../../data/reports/eurc-2022-06.json";
import r1 from "../../../data/reports/eurc-2022-07.json";
import r2 from "../../../data/reports/eurc-2022-08.json";
import r3 from "../../../data/reports/eurc-2022-09.json";
import r4 from "../../../data/reports/eurc-2022-10.json";
import r5 from "../../../data/reports/eurc-2022-11.json";
import r6 from "../../../data/reports/eurc-2022-12.json";
import r7 from "../../../data/reports/eurc-2023-01.json";
import r8 from "../../../data/reports/eurc-2023-02.json";
import r9 from "../../../data/reports/eurc-2023-03.json";
import r10 from "../../../data/reports/eurc-2023-04.json";
import r11 from "../../../data/reports/eurc-2023-05.json";
import r12 from "../../../data/reports/eurc-2023-06.json";
import r13 from "../../../data/reports/eurc-2023-07.json";
import r14 from "../../../data/reports/eurc-2023-08.json";
import r15 from "../../../data/reports/eurc-2023-09.json";
import r16 from "../../../data/reports/eurc-2023-10.json";
import r17 from "../../../data/reports/eurc-2023-11.json";
import r18 from "../../../data/reports/eurc-2023-12.json";
import r19 from "../../../data/reports/eurc-2024-01.json";
import r20 from "../../../data/reports/eurc-2024-02.json";
import r21 from "../../../data/reports/eurc-2024-03.json";
import r22 from "../../../data/reports/eurc-2024-04.json";
import r23 from "../../../data/reports/eurc-2024-05.json";
import r24 from "../../../data/reports/eurc-2024-06.json";
import r25 from "../../../data/reports/eurc-2024-07.json";
import r26 from "../../../data/reports/eurc-2024-08.json";
import r27 from "../../../data/reports/eurc-2024-09.json";
import r28 from "../../../data/reports/eurc-2024-10.json";
import r29 from "../../../data/reports/eurc-2024-11.json";
import r30 from "../../../data/reports/eurc-2024-12.json";
import r31 from "../../../data/reports/eurc-2025-01.json";
import r32 from "../../../data/reports/eurc-2025-02.json";
import r33 from "../../../data/reports/eurc-2025-03.json";
import r34 from "../../../data/reports/eurc-2025-04.json";
import r35 from "../../../data/reports/eurc-2025-05.json";
import r36 from "../../../data/reports/eurc-2025-06.json";
import r37 from "../../../data/reports/eurc-2025-07.json";
import r38 from "../../../data/reports/eurc-2025-08.json";
import r39 from "../../../data/reports/eurc-2025-09.json";
import r40 from "../../../data/reports/eurc-2025-10.json";
import r41 from "../../../data/reports/eurc-2025-11.json";
import r42 from "../../../data/reports/eurc-2025-12.json";
import r43 from "../../../data/reports/eurc-2026-01.json";
import r44 from "../../../data/reports/eurc-2026-02.json";
import r45 from "../../../data/reports/eurc-2026-03.json";
import r46 from "../../../data/reports/eurc-2026-04.json";
import r47 from "../../../data/reports/eurc-2026-05.json";
import r48 from "../../../data/reports/usdc-2018-10.json";
import r49 from "../../../data/reports/usdc-2018-11.json";
import r50 from "../../../data/reports/usdc-2018-12.json";
import r51 from "../../../data/reports/usdc-2019-01.json";
import r52 from "../../../data/reports/usdc-2019-02.json";
import r53 from "../../../data/reports/usdc-2019-03.json";
import r54 from "../../../data/reports/usdc-2019-04.json";
import r55 from "../../../data/reports/usdc-2019-05.json";
import r56 from "../../../data/reports/usdc-2019-06.json";
import r57 from "../../../data/reports/usdc-2019-07.json";
import r58 from "../../../data/reports/usdc-2019-08.json";
import r59 from "../../../data/reports/usdc-2019-09.json";
import r60 from "../../../data/reports/usdc-2019-10.json";
import r61 from "../../../data/reports/usdc-2019-11.json";
import r62 from "../../../data/reports/usdc-2019-12.json";
import r63 from "../../../data/reports/usdc-2020-01.json";
import r64 from "../../../data/reports/usdc-2020-02.json";
import r65 from "../../../data/reports/usdc-2020-03.json";
import r66 from "../../../data/reports/usdc-2020-04.json";
import r67 from "../../../data/reports/usdc-2020-05.json";
import r68 from "../../../data/reports/usdc-2020-06.json";
import r69 from "../../../data/reports/usdc-2020-07.json";
import r70 from "../../../data/reports/usdc-2020-08.json";
import r71 from "../../../data/reports/usdc-2020-09.json";
import r72 from "../../../data/reports/usdc-2020-10.json";
import r73 from "../../../data/reports/usdc-2020-11.json";
import r74 from "../../../data/reports/usdc-2020-12.json";
import r75 from "../../../data/reports/usdc-2021-01.json";
import r76 from "../../../data/reports/usdc-2021-02.json";
import r77 from "../../../data/reports/usdc-2021-03.json";
import r78 from "../../../data/reports/usdc-2021-04.json";
import r79 from "../../../data/reports/usdc-2021-05.json";
import r80 from "../../../data/reports/usdc-2021-06.json";
import r81 from "../../../data/reports/usdc-2021-07.json";
import r82 from "../../../data/reports/usdc-2021-08.json";
import r83 from "../../../data/reports/usdc-2021-09.json";
import r84 from "../../../data/reports/usdc-2021-10.json";
import r85 from "../../../data/reports/usdc-2021-11.json";
import r86 from "../../../data/reports/usdc-2021-12.json";
import r87 from "../../../data/reports/usdc-2022-01.json";
import r88 from "../../../data/reports/usdc-2022-02.json";
import r89 from "../../../data/reports/usdc-2022-03.json";
import r90 from "../../../data/reports/usdc-2022-04.json";
import r91 from "../../../data/reports/usdc-2022-05.json";
import r92 from "../../../data/reports/usdc-2022-06.json";
import r93 from "../../../data/reports/usdc-2022-07.json";
import r94 from "../../../data/reports/usdc-2022-08.json";
import r95 from "../../../data/reports/usdc-2022-09.json";
import r96 from "../../../data/reports/usdc-2022-10.json";
import r97 from "../../../data/reports/usdc-2022-11.json";
import r98 from "../../../data/reports/usdc-2022-12.json";
import r99 from "../../../data/reports/usdc-2023-01.json";
import r100 from "../../../data/reports/usdc-2023-02.json";
import r101 from "../../../data/reports/usdc-2023-03.json";
import r102 from "../../../data/reports/usdc-2023-04.json";
import r103 from "../../../data/reports/usdc-2023-05.json";
import r104 from "../../../data/reports/usdc-2023-06.json";
import r105 from "../../../data/reports/usdc-2023-07.json";
import r106 from "../../../data/reports/usdc-2023-08.json";
import r107 from "../../../data/reports/usdc-2023-09.json";
import r108 from "../../../data/reports/usdc-2023-10.json";
import r109 from "../../../data/reports/usdc-2023-11.json";
import r110 from "../../../data/reports/usdc-2023-12.json";
import r111 from "../../../data/reports/usdc-2024-01.json";
import r112 from "../../../data/reports/usdc-2024-02.json";
import r113 from "../../../data/reports/usdc-2024-03.json";
import r114 from "../../../data/reports/usdc-2024-04.json";
import r115 from "../../../data/reports/usdc-2024-05.json";
import r116 from "../../../data/reports/usdc-2024-06.json";
import r117 from "../../../data/reports/usdc-2024-07.json";
import r118 from "../../../data/reports/usdc-2024-08.json";
import r119 from "../../../data/reports/usdc-2024-09.json";
import r120 from "../../../data/reports/usdc-2024-10.json";
import r121 from "../../../data/reports/usdc-2024-11.json";
import r122 from "../../../data/reports/usdc-2024-12.json";
import r123 from "../../../data/reports/usdc-2025-01.json";
import r124 from "../../../data/reports/usdc-2025-02.json";
import r125 from "../../../data/reports/usdc-2025-03.json";
import r126 from "../../../data/reports/usdc-2025-04.json";
import r127 from "../../../data/reports/usdc-2025-05.json";
import r128 from "../../../data/reports/usdc-2025-06.json";
import r129 from "../../../data/reports/usdc-2025-07.json";
import r130 from "../../../data/reports/usdc-2025-08.json";
import r131 from "../../../data/reports/usdc-2025-09.json";
import r132 from "../../../data/reports/usdc-2025-10.json";
import r133 from "../../../data/reports/usdc-2025-11.json";
import r134 from "../../../data/reports/usdc-2025-12.json";
import r135 from "../../../data/reports/usdc-2026-01.json";
import r136 from "../../../data/reports/usdc-2026-02.json";
import r137 from "../../../data/reports/usdc-2026-03.json";
import r138 from "../../../data/reports/usdc-2026-04.json";
import r139 from "../../../data/reports/usdc-2026-05.json";

export const reports: Report[] = [
  r0,
  r1,
  r2,
  r3,
  r4,
  r5,
  r6,
  r7,
  r8,
  r9,
  r10,
  r11,
  r12,
  r13,
  r14,
  r15,
  r16,
  r17,
  r18,
  r19,
  r20,
  r21,
  r22,
  r23,
  r24,
  r25,
  r26,
  r27,
  r28,
  r29,
  r30,
  r31,
  r32,
  r33,
  r34,
  r35,
  r36,
  r37,
  r38,
  r39,
  r40,
  r41,
  r42,
  r43,
  r44,
  r45,
  r46,
  r47,
  r48,
  r49,
  r50,
  r51,
  r52,
  r53,
  r54,
  r55,
  r56,
  r57,
  r58,
  r59,
  r60,
  r61,
  r62,
  r63,
  r64,
  r65,
  r66,
  r67,
  r68,
  r69,
  r70,
  r71,
  r72,
  r73,
  r74,
  r75,
  r76,
  r77,
  r78,
  r79,
  r80,
  r81,
  r82,
  r83,
  r84,
  r85,
  r86,
  r87,
  r88,
  r89,
  r90,
  r91,
  r92,
  r93,
  r94,
  r95,
  r96,
  r97,
  r98,
  r99,
  r100,
  r101,
  r102,
  r103,
  r104,
  r105,
  r106,
  r107,
  r108,
  r109,
  r110,
  r111,
  r112,
  r113,
  r114,
  r115,
  r116,
  r117,
  r118,
  r119,
  r120,
  r121,
  r122,
  r123,
  r124,
  r125,
  r126,
  r127,
  r128,
  r129,
  r130,
  r131,
  r132,
  r133,
  r134,
  r135,
  r136,
  r137,
  r138,
  r139
] as Report[];

export const usdcReports = reports.filter(r => r.kind === "usdc");
export const eurcReports = reports.filter(r => r.kind === "eurc");
