// Generate src/data/reports/index.ts that statically imports every JSON
// produced by parse.mjs, so Next.js can bundle them without a runtime fs.
import { readdirSync, writeFileSync } from "node:fs";

const files = readdirSync("data/reports")
  .filter(f => f.endsWith(".json") && !f.startsWith("_"))
  .sort();

const imports = files
  .map((f, i) => `import r${i} from "../../../data/reports/${f}";`)
  .join("\n");

const arr = files.map((_, i) => `r${i}`).join(",\n  ");

const ts = `// AUTO-GENERATED by scripts/build-index.mjs. Do not edit by hand.

export type Kind = "usdc" | "eurc";
export type Format = "grant-thornton" | "deloitte";

export type Composition = {
  treasuries: number;
  repos: number;
  cashInFund: number;
  cashAtBanks: number;
  totalReserveFund: number | null;
  totalOther: number | null;
  totalReserveAssets: number | null;
};

export type Series = {
  date: string;
  circulation: number;
  reserveTotal: number;
  composition: Composition | null;
};

export type Report = {
  kind: Kind;
  year: number;
  month: number;
  format: Format;
  reportDates: string[];
  series: Series[];
  warnings: string[];
  sourcePdf: string;
  localPdf: string;
  sourceUrl: string;
  overrideNote?: string;
};

${imports}

export const reports: Report[] = [
  ${arr}
] as Report[];

export const usdcReports = reports.filter(r => r.kind === "usdc");
export const eurcReports = reports.filter(r => r.kind === "eurc");
`;

writeFileSync("src/data/reports/index.ts", ts);
console.log(`Wrote src/data/reports/index.ts with ${files.length} reports.`);
